numbbo/coco

do.py
=> hg_revision out-commented in do.py

build/python/setup.py.in, do.py, tools/cocoutils.py
=> Nikos local master branch

build/c/Makefile, build/c/Makefile_win_gcc, build/c/mo/Makefile, build/c/mo/Makefile_win_gcc, build/c/mo/demo_mo.c, src/bbob2009_logger.c, src/bbob2009_suite.c, src/biobjective_suite_300.c, src/coco_utilities.c, src/f_bbob_step_ellipsoid.c, src/f_gallagher.c, src/f_katsuura.c, src/f_lunacek_bi_rastrigin.c, src/log_nondominating.c, src/mo_paretofiltering.c, src/mo_recorder.c, src/mo_recorder.h
c89 compilation enforced,
new Windows Makefile for MO-BBOB,
correction of coco_create_path(...) for Windows users without Cygwin
=> Dimo master

build/c/Makefile, build/c/mo/Makefile, do.py, src/coco_utilities.c
Updated the makefiles so that changes in .c files trigger rebuilding.
Fixed Windows build (the definition of S_IRWXU).
=> Feature mo

build/java/README.txt
Added description on how to compile and build the Java demo under Windows and Cygwin's x86_64-w64-mingw32-gcc compiler
=> Updated a readme file

code-postprocessing/bbob_pproc/findfiles.py
=> Master test ci 1

code-experiments/build/java/README.txt, code-experiments/build/python/coco_test.py, code-experiments/build/python/cython/interface.pyx, code-experiments/build/python/example.py, code-experiments/build/python/example_experiment.py, code-experiments/build/python/python/__init__.py, code-experiments/build/python/python/exceptions.py, code-experiments/src/coco_observer.c, code-experiments/src/coco_suite.c, do.py
`build/python/demo.py` "moved" to `build/python/example_experiment.py`
=> New interface in python compliant with new C interface

code-experiments/build/python/cython/interface.pyx
=> removed deprecated__coco_... functions in python interface.pyx

code-experiments/build/c/example_experiment.c
…ions as in the other languages
=> correction of C example experiment

code-experiments/src/coco_runtime_c.c
modified:   code-experiments/src/coco_runtime_c.c
=> Messages in coco_runtime_c.c prepended with "COCO "

code-experiments/tools/cocoutils.py, do.py
modified:   tools/cocoutils.py
modified:   ../do.py
=> do.py backported to Python 2.6

code-experiments/tools/cocoutils.py, do.py
however untested, as I was hesitant to unstall git.
modified:   ../../tools/cocoutils.py
modified:   ../../../do.py
=> removed git dependency on do.py

code-experiments/src/logger_biobj_avl_tree.c
modified:   logger_biobj_avl_tree.c
=> C initialize warnings are gone now

code-experiments/build/python/example_experiment.py
=> nicer output in the Python example experiment

code-experiments/build/python/example_experiment.py
=> cosmetics in example_experiment.py

code-experiments/src/coco.h, code-experiments/src/coco_generics.c, code-experiments/src/coco_observer.c, code-experiments/src/coco_random.c, code-experiments/src/coco_string.c, code-experiments/src/coco_suite.c, code-experiments/src/coco_utilities.c, docs/code-documentation/C/Doxyfile, docs/code-documentation/C/README.md
Added comments to coco.h and other source files and made some minor changes for the sake of consistency.
=> Created the minimal documentation for the first release.

do.py
to test-postprocessing
modified:   do.py
=> small revision of do.py help and renaming test-post-processing

code-experiments/build/python/cython/interface.c, code-experiments/build/python/cython/interface.pyx, code-experiments/build/python/example_experiment.py
modified:   code-experiments/build/python/cython/interface.c
=> comments added and code cosmetics

code-experiments/build/matlab/exampleexperiment.m, code-experiments/tools/cocoutils.py, do.py
and do.py is now case independent
=> git_version() now might work when git is not available

code-experiments/build/python/cython/interface.c, code-experiments/build/python/cython/interface.pyx, code-experiments/build/python/example_experiment.py, code-experiments/build/python/python/__init__.py
modified:   code-experiments/build/python/cython/interface.c
modified:   code-experiments/build/python/python/__init__.py
=> log level Python interface revised

code-experiments/build/java/README.txt
overly technical.
modified:   README.txt
=> improved on java readme, still needs major revision seems

code-experiments/build/matlab/setup.m, code-experiments/examples/bbob-biobj-matlab-smsemoa/setup.m
took out uncommented and never used Octave stuff
=> solved printf vs. fprintf in Matlab/Octave wrapper,

code-postprocessing/bbob_pproc/compall/pprldmany.py, code-postprocessing/bbob_pproc/genericsettings.py, code-postprocessing/bbob_pproc/ppfigdim.py, code-postprocessing/bbob_pproc/ppfigparam.py, code-postprocessing/bbob_pproc/pprldistr.py, code-postprocessing/bbob_pproc/pproc.py, code-postprocessing/bbob_pproc/rungeneric1.py, code-postprocessing/bbob_pproc/rungeneric2.py, code-postprocessing/bbob_pproc/rungenericmany.py
=> Fix for the ECDFs of single functions.

code-experiments/build/python/demo.py, code-experiments/src/coco.h, code-experiments/src/coco_suite.c, code-experiments/src/logger_biobj.c
=> Removed the coco_optimizer_t type and the coco_run_benchmark() function.

code-postprocessing/bbob_pproc/genericsettings.py, code-postprocessing/bbob_pproc/pproc.py
=> Expected number of instances for bi-objective case is 10.

code-postprocessing/bbob_pproc/ppfig.py
=> Clickable figures in html.

code-experiments/build/matlab/octave_coco.bat.in, do.py
still gives some warnings during compilation
=> new octave_coco.bat file to circumvent problems under Windows,

code-experiments/src/coco_observer.c, code-experiments/src/observer_biobj.c, code-experiments/test/unit-test/test_coco_observer.c, docs/code-documentation/C/README.md
Updated some comments in the C code.
=> Updated readme of coco-doc/C.

code-experiments/src/coco_observer.c, code-experiments/src/coco_utilities.c, code-experiments/src/large_scale_transformations.c, code-experiments/src/logger_bbob.c, code-experiments/src/suite_biobj.c, code-experiments/test/unit-test/test_coco_observer.c
=> Fixed failing unit test

code-experiments/build/c/example_experiment.c, code-experiments/build/python/example_experiment.py
modified:   code-experiments/build/c/example_experiment.c
=> tentative example experiment with restarts in C

code-experiments/build/matlab/exampleexperiment.m, code-experiments/examples/bbob-biobj-matlab-smsemoa/run_smsemoa_on_bbob_biobj.m, docs/bbob-biobj/functions/source/our-approach.rst
...and added some more text to documentation
=> corrected mistakes in using endif in Matlab wrapper

docs/bbob-biobj/functions/source/introduction.rst, docs/bbob-biobj/functions/source/our-approach.rst
one correction in our-approach.rst
=> written introduction of bbob-biobj function documentation,

code-experiments/build/python/example_experiment.py
modified:   example_experiment.py
=> added timing printouts that can directly used in a workshop paper

code-experiments/build/python/cython/interface.c, code-experiments/build/python/cython/interface.pyx
modified:   code-experiments/build/python/cython/interface.c
=> coco_problem_get_initial_solution ported to Python interface

code-experiments/build/python/cython/interface.c, code-experiments/build/python/cython/interface.pyx
modified:   code-experiments/build/python/cython/interface.c
=> cython constraints interface

code-experiments/build/python/example_experiment.py
modified:   example_experiment.py
=> fine tuning of python example, output indicates number of restarts

code-experiments/build/matlab/cocoCall.c
+ removal of other unnecessary variable declarations which led to other memory leaks
=> fixed bug #804 in Matlab wrapper

code-postprocessing/bbob_pproc/compall/ppfigs.py, code-postprocessing/bbob_pproc/config.py, code-postprocessing/bbob_pproc/genericsettings.py, code-postprocessing/bbob_pproc/latex_commands_for_html.html, code-postprocessing/bbob_pproc/ppfig.py, code-postprocessing/bbob_pproc/ppfigdim.py, code-postprocessing/bbob_pproc/pprldistr.py, code-postprocessing/bbob_pproc/pproc.py, code-postprocessing/bbob_pproc/pptable.py, code-postprocessing/bbob_pproc/preparehtml.py, code-postprocessing/bbob_pproc/preparetexforhtml.py, code-postprocessing/bbob_pproc/rungeneric1.py, code-postprocessing/bbob_pproc/rungeneric2.py, code-postprocessing/bbob_pproc/rungenericmany.py
Plus further refactoring of the postprocessing with this respect. Will close issue #706 as soon as CI tests go through on devel-test2 branch.
=> moving pptable's targetsOfInterest to genericsettings

code-postprocessing/bbob_pproc/compall/ppfigs.py, code-postprocessing/bbob_pproc/compall/pprldmany.py, code-postprocessing/bbob_pproc/genericsettings.py, code-postprocessing/bbob_pproc/latex_commands_for_html.html, code-postprocessing/bbob_pproc/rungeneric1.py, code-postprocessing/latex-templates/templateBIOBJarticle.tex
thanks to the plots by @dtusar
=> First complete  version of bbob-biobj LaTeX template

docs/coco-doc/C/README.md
@brockho Just a reminder for you to run doxygen on this file :)
=> Updated coco-doc/C with information about timing experiment.

code-experiments/build/python/example_experiment.py
=> added table printout of timings to python example experiment

code-postprocessing/latex-templates/templateBIOBJarticle.tex
=> LaTeX table now in landscape format for biobjective template,

code-postprocessing/bbob_pproc/config.py
=> --expensive flag not accessible in biobjective case anymore

docs/coco-generic/coco-perf-assessment/source/index.rst
It seems that my text editor has deleted some spaces at the end of the lines by itself, so it looks as if more changes were done. I've only reviewed the document up to "Missing values".
=> Started reviewing the general performance assessment.

code-experiments/tools/cocoutils.py, code-postprocessing/bbob_pproc/__init__.py, code-postprocessing/bbob_pproc/ppfig.py, code-postprocessing/bbob_pproc/toolsdivers.py, do.py
(now it should e.g. work also without git being installed)
=> tried to handle the COCO version number within the plots better

docs/bbob-biobj/perf-assessment/source/index.rst, docs/coco-generic/coco-perf-assessment/source/index.rst
started to address some of my TODOs
=> reverted mistakes during conflict,

docs/coco-generic/coco-perf-assessment/source/index.rst
added correct references to COCO papers already on arXiv
=> first trial to write about problem definition with quality indicators,

docs/bbob-biobj/perf-assessment/source/index.rst
also added the missing references such that the biobjective performance assessment documentation seems complete
=> finished implementing Tobias' suggestions,

code-postprocessing/latex-templates/acmcopyright.sty, code-postprocessing/latex-templates/comment.sty, code-postprocessing/latex-templates/sig-alternate.cls, code-postprocessing/latex-templates/templateBBOBarticle.tex, code-postprocessing/latex-templates/templateBBOBcmp.tex, code-postprocessing/latex-templates/templateBBOBmany.tex, code-postprocessing/latex-templates/templateBIOBJarticle.tex
added sentence about COCO version to all LaTeX templates
=> updated sig-alternate class for LaTeX templates to newest ACM version,

code-postprocessing/bbob_pproc/__main__.py, code-postprocessing/setup.py.in
...at least on the linux and mac slaves
=> fix error in postprocessing from new ACM stylefile

code-postprocessing/latex-templates/bbob.bib, code-postprocessing/latex-templates/templateBBOBarticle.tex, code-postprocessing/latex-templates/templateBBOBcmp.tex, code-postprocessing/latex-templates/templateBBOBmany.tex, code-postprocessing/latex-templates/templateBIOBJarticle.tex
update of the paragraphs citing those works
=> update of BibTeX entry with the missing two documents,

code-postprocessing/latex-templates/bbob.bib, code-postprocessing/latex-templates/templateBBOBarticle.tex, code-postprocessing/latex-templates/templateBBOBcmp.tex, code-postprocessing/latex-templates/templateBBOBmany.tex, code-postprocessing/latex-templates/templateBIOBJarticle.tex
outcommented not mandatory ACM classifications,
added links to the new documentation also for the single-objective templates
=> changed comments on top of LaTeX files according to new ACM style used,

code-postprocessing/bbob_pproc/compall/pptables.py, code-postprocessing/bbob_pproc/config.py, code-postprocessing/bbob_pproc/genericsettings.py, code-postprocessing/bbob_pproc/rungenericmany.py, code-postprocessing/bbob_pproc/testbedsettings.py, code-postprocessing/latex-templates/templateBBOBmany.tex
changes towards multiple algo template for `bbob-biobj` testbed
=> corrected wrong caption (issue #980),

code-postprocessing/latex-templates/templateBIOBJmultiple.tex
corrected bug introduced in previous commit in the same file
=> updated tables in multi-algo bbob-biobj template,

code-experiments/src/f_griewank_rosenbrock.c, code-experiments/src/f_rosenbrock.c
Work-around that should probably not be the "final" solution to the problem.
=> Addressing Remaining Failed Continuous Integration Tests

docs/bbob-biobj/functions/code/generate_plots.py, docs/bbob-biobj/functions/code/plots_alongDirections.py
...displaying the objective vectors along several lines through the search space (through optima in random direction, through optima along coordinate axes, through both optima, and in two random directions)
=> finished publishable version of objective space plots

code-experiments/build/python/coco_test.py
Uncomment 'testmod(interface)' for tracking a segmentation fault (`issue #1103`) reported by Wassim.
=> Uncomment 'testmod(interface)' for tracking a segmentation fault

code-preprocessing/log-reconstruction/merge_lines_in_info_files.py, docs/bbob-biobj/functions/code/generate_plots.py
plus downsampling in the decision space plots for the `bbob-biobj` function suite documentation
=> new script to merge lines in reconstructed .info files

code-postprocessing/bbob_pproc/__main__.py, code-postprocessing/bbob_pproc/compall/pptables.py, code-postprocessing/bbob_pproc/rungeneric.py, do.py
and removed the `--omit-single` option from the first nightly-build test
=> solved bug #1109 (missing function numbers in html tables for >2 algos)

code-experiments/build/python/example_experiment.py, code-postprocessing/bbob_pproc/__main__.py, do.py
To this end, the `example_experiment.py` was changed to handle experiments with different test suites through `__main__` in different output folders more easily.
=> integration test for newly generated data (addressing #1144)

code-postprocessing/bbob_pproc/__main__.py, do.py
This issue has been already reported in March 2016, but unfortunately, we just found time to fix this now.
=> Fixed bug in python reported by Simon Wessing

code-postprocessing/cocopp/captions.py, code-postprocessing/cocopp/compall/ppfigs.py, code-postprocessing/cocopp/config.py, code-postprocessing/cocopp/latex_commands_for_html.html, code-postprocessing/cocopp/ppfigdim.py, code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/latex-templates/acmart.cls, code-postprocessing/latex-templates/bbob.bib, code-postprocessing/latex-templates/templateBBOBarticle.tex, code-postprocessing/latex-templates/templateBBOBcmp.tex, code-postprocessing/latex-templates/templateBBOBmany.tex, code-postprocessing/latex-templates/templateBIOBJarticle.tex
...and its newest ACM style templates (except for multiple `bbob-biobj` data set template)
=> Testing dimo-develop-latex

code-postprocessing/cocopp/captions.py, code-postprocessing/cocopp/comp2/pptable2.py, code-postprocessing/cocopp/compall/ppfigs.py, code-postprocessing/cocopp/compall/pptables.py, code-postprocessing/cocopp/pprldistr.py, code-postprocessing/cocopp/rungeneric.py, code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/cocopp/rungeneric2.py, code-postprocessing/latex-templates/templateBIOBJarticle.tex, code-postprocessing/latex-templates/templateBIOBJmultiple.tex
at the same time, issues #1308 and #1238 have been addressed
=> test dimo-develop-latex branch

code-experiments/src/c_linear.c, code-experiments/src/f_rastrigin.c, code-experiments/src/logger_bbob.c, do.py
- adding missing coco_random_free() in c_linear.c
- adding memory test for constraint tesbed in do.py
- fixing bug related to sprintf in logger_bbob.c
- adding missing coco_free_memory() in f_rastrigin.c
=> Phrsampaio master testmerge

code-postprocessing/cocopp/comp2/ppfig2.py
Hi @nikohansen: would you be so kind and check that the code, I deleted, is really doing nothing?
=> small clean up ppfig2.py

code-experiments/src/c_linear.c, code-experiments/src/f_linear_slope.c, code-experiments/src/f_rastrigin.c, code-experiments/src/f_sharp_ridge.c, code-experiments/src/logger_bbob.c, code-experiments/src/suite_biobj_ext.c, code-experiments/src/suite_cons_bbob.c
For the last one, I am quite confused as all transformations actually do the same as the `bbob` logger (to be discussed tomorrow).
Tests are triggered on `devel-test3` branch and should finish later tonight (no problem seen so far on my Windows laptop).
=> addressing issue #1350 up to one final warning

code-experiments/build/python/example_experiment.py, code-experiments/src/coco_observer.c, code-experiments/src/logger_bbob.c
Note: the example experiment in Python is known to be suboptimal at this point in time (see #1384).
=> corrected bbob logger to address issue #1383

code-postprocessing/helper-scripts/changeAlgIdAndComment.py
...to handle `bbob-biobj(-ext)` data folders as well
=> update of changeAlgIdAndComment.py

code-postprocessing/cocopp/algportfolio.py
=> Fixed exception handling typo in algportfolio.py

do.py
A couple of help text additions and corrections
=> Islandblue issue1436

code-postprocessing/cocopp/findfiles.py, code-postprocessing/cocopp/pproc.py, code-postprocessing/cocopp/test.py
at the same time, corrected bug that caused problems according to the hv-hash in python 3
=> allow for zip files as input files (issue #35),

do.py
=> Reset default package install location to system.

code-postprocessing/cocopp/findfiles.py, code-postprocessing/cocopp/pproc.py, code-postprocessing/cocopp/test.py
I suspect that we will see the same valgrind errors as in the open pull request #1509.
=> test dimo-issue35 branch once more (see #1520)

code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/cocopp/rungenericmany.py
Should print now for both single and multiple algorithms.
=> Print output folder at the end of post-processing (issue #1497)

code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/cocopp/rungenericmany.py
=> Remove condition on printing output folder after pp #1497

code-experiments/build/python/example_experiment_non_anytime.py, code-postprocessing/cocopp/__init__.py, code-postprocessing/cocopp/bestalg.py, code-postprocessing/cocopp/cococommands.py, code-postprocessing/cocopp/findfiles.py, code-postprocessing/cocopp/pproc.py, code-postprocessing/cocopp/test.py
=> simplification of anytime evaluation class

code-postprocessing/cocopp/readalign.py
As discussed in #1466 and agreed in COCO meeting on 10.10.2017.
=> Fix issue #1466

code-postprocessing/cocopp/ppfig.py
...however, the code is ugly :-( as is most of the code producing the html at the moment. The choice of which figures to include should not depend on which plots are lying around but on which suite/data_format combination is postprocessed, I would guess.
=> solved issue #1592 ("figureless index.html files")

code-experiments/build/java/CocoJNI.c, code-experiments/build/java/CocoJNI.java, code-experiments/build/java/Problem.java, code-experiments/build/python/cython/interface.c, code-experiments/build/python/cython/interface.pyx, code-experiments/src/coco.h, code-experiments/src/coco_problem.c, code-experiments/test/unit-test/test_coco_problem.c
Exposed the largest f-values of interest in `coco.h` and created interfaces in Python and Java
=> Biobj expose reference

code-postprocessing/cocopp/__main__.py, code-postprocessing/cocopp/comp2/ppfig2.py, code-postprocessing/cocopp/ppfig.py
=> trying to fix incompatibility with matplotlib version 2.0.2 -> 2.1

code-postprocessing/cocopp/compall/ppfigs.py
...but not directly pushed to `development` to let first the tests on the master branch run through cleanly.
=> addressed issue #1643

code-postprocessing/cocopp/pptable.py, code-postprocessing/latex-templates/templateBBOBarticle.tex, code-postprocessing/latex-templates/templateBBOBcmp.tex, code-postprocessing/latex-templates/templateBBOBmany.tex, code-postprocessing/latex-templates/templateBIOBJarticle.tex, code-postprocessing/latex-templates/templateBIOBJmultiple.tex
All LaTeX templates should now work again with the latest matplotlib version.
=> addressed issue #1502

code-experiments/src/f_katsuura.c
where it seems the problem was the initial xopt to be all ones instead of all zeros.
=> fix best parameter representation of f23

code-experiments/build/c/example_experiment.c, code-experiments/src/coco_utilities.c, code-experiments/test/integration-test/test_bbob-constrained.c
This is the same than pull request #1694 which was coming from the devel-test2 branch and was stored temporarily in the pullrequest-1694 branch to free the test branch.
If not mistaken, some of the tests have not gone through on this code yet.
=> Pullrequest 1694

code-postprocessing/cocopp/ppfig.py
Erroneous markers in fixed-target ECDF
=> Fix for issue #1670

code-experiments/src/logger_bbob.c, code-postprocessing/cocopp/dataformatsettings.py
and f + 1e3 sum gi as indicator in bbob-new2 as dataformat, addressing #1756,#1755,#1728,#1706
=> logging single digit constraints values

code-experiments/src/c_linear.c
Found one remaining compiler warning that didn't show on any of the Jenkins machines...
=> Took care of a compiler warning.

code-postprocessing/cocopp/config.py, code-postprocessing/cocopp/dataformatsettings.py, code-postprocessing/cocopp/pproc.py, code-postprocessing/cocopp/readalign.py, code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/cocopp/rungenericmany.py, code-postprocessing/cocopp/testbedsettings.py
solving issues #1804 and #1800 (Reader.idxData was not set to the
constrained index column in the second call)
=> remove dataformatsetting from testbedsetting

do.py
Added classpath to java build commands
=> Fix issue 1910

appveyor.yml, code-postprocessing/cocopp/compall/pprldmany.py, code-postprocessing/cocopp/ppfig.py, code-postprocessing/cocopp/pprldistr.py
should be merged as soon as tests run through on Jenkins
=> addressing issue 1923 (also for coco-docs paper)

do.py
Added `'--gen-suppressions=yes'` option to leak check in order to hopefully solve our problem on the master branch.
=> Suppression option in valgrind

code-postprocessing/cocopp/TODO, code-postprocessing/cocopp/bestalg.py, code-postprocessing/cocopp/captions.py, code-postprocessing/cocopp/compall/ppfigs.py, code-postprocessing/cocopp/compall/pprldmany.py, code-postprocessing/cocopp/compall/pptables.py, code-postprocessing/cocopp/config.py, code-postprocessing/cocopp/ppfigdim.py, code-postprocessing/cocopp/pprldistr.py, code-postprocessing/cocopp/pproc.py, code-postprocessing/cocopp/preparetexforhtml.py, code-postprocessing/cocopp/rungeneric.py, code-postprocessing/cocopp/rungeneric1.py, code-postprocessing/cocopp/rungenericmany.py, code-postprocessing/cocopp/testbedsettings.py
...replacing `get_suite` and `testbed_name` with `suite_name` property in DataSet (#1933)
+
filtering DataSets also for a single algorithm to allow postprocessing data from different test suites (#1960)
=> fixing issues #1933 and #1960

.github/workflows/meson.yml
Add a Github workflow to build the C example using meson on both Linux, MacOS and Windows.
=> Add meson CI

.github/workflows/cmake.yml
Improve the CMake CI workflow to build both on Linux and Windows in Release and Debug configuration.
=> Improve CMake CI

code-experiments/build/rust/Cargo.toml, code-experiments/build/rust/coco-sys/Cargo.toml, code-experiments/build/rust/coco-sys/build.rs, code-experiments/build/rust/coco-sys/src/lib.rs, code-experiments/build/rust/coco-sys/wrapper.h, code-experiments/build/rust/src/lib.rs, do.py
`coco-sys`:
- Make build self-contained (closes #2171)
- Add `coco_problem_get_best_value`
- Add `coco_problem_get_final_target_fvalue1`
`coco-rs`: 
- Implement `Clone` for `Suite`
- Add `Suite::problem_by_function_dimension_instance_index`
- Add `Problem::final_target_value`
- Add `Problem::best_value`
=> Update Rust bindings to 0.6

code-experiments/build/python/demo.py
solve unmatched brackets problem at demo.py
=> solve SyntaxError: unmatched ')'

code-experiments/build/java/CocoJNI.c, code-experiments/build/java/CocoJNI.java, code-experiments/build/java/ExampleExperiment.java, code-experiments/build/java/Problem.java, code-experiments/build/java/Suite.java
Added some functions to the Java interface to enable the usage of COCO problems separately (not within a benchmarking experiment).
=> Devel test2

.gitignore, code-experiments/build/c/example_experiment.c, code-experiments/src/coco_observer.c, code-experiments/src/coco_utilities.c, code-experiments/src/logger_bbob.c, code-experiments/src/observer_bbob.c
Fixed issue with repeated file names in a single info file + increased the limit for unique files/folders.
=> Fixed logger filenames

DEVELOPMENT.md
Change flag to update subcommand to the correct --file. Fixes #2326.
=> Update conda update command
