- code-experiments/src/large_scale_transformations.c
- code-experiments/src/logger_bbob.c
use of bbob2009_fmax instead of fmax since it seems to make the windows builds fail
> use of bbob2009_fmax instead of fmax since it seems to make the windows builds fail

- code-postprocessing/bbob_pproc/__init__.py
- code-postprocessing/bbob_pproc/__main__.py
make the postprocessing test run on Linux (adding matplotlib.use('Agg'))
modified:   bbob_pproc/__init__.py
modified:   bbob_pproc/__main__.py
> bugfix for post-processing testing on Linux machine

- code-experiments/src/logger_biobj.c
- code-experiments/src/observer_biobj.c
When the observer should log the indicator in the info file, it checks whether the current function is different from the previous function observed. It does not check whether the dimensionality is different. this breaks cases where the same function is evaluated in different dimensions.
problem came up in #707
> fixed issue in observer

- code-experiments/build/python/cython/interface.c
- code-experiments/build/python/cython/interface.pyx
- code-experiments/build/python/python/__init__.py
are now visible when using ``pydoctor --docformat=restructuredtext --make-html`` to generate the api docs.
> docstrings in cocoex

- code-experiments/src/transform_vars_permutation_helpers.c
- code-postprocessing/cocopp/preparetexforhtml.py
- code-postprocessing/cocopp/testbedsettings.py
Added a temporary fix for #1102 `(if dimension <= 40)` and current tests showed that it should also fix  #1231 
( I now longer see increased memory usage when on a python console and running 
`suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160,320,640')`
multiple times in the same python instance.)
Also, added large-scale scenario to `preparetexforhtml.py` which should, in theory and once rerun to update `latex_commands_for_html.html`, fix #1286
> Fixing Memory Leaks and Backward Compatibility Issues in the Large-Scale Testsuite

- .circleci/config.yml
- appveyor.yml
- code-postprocessing/cocopp/grayscalesettings.py
- code-preprocessing/archive-update/python/archive_load_data.py
- code-preprocessing/log-reconstruction/test_reconstruction.py
Hi @nikohansen and @brockho. Now that you have a new CI set up, we should make it useful. I suggest to run all the available COCO unit tests. I have already tried to add your unit tests to `.circleci/config.yml` and `appveyor.yml`, however, I struggle to make the tests pass.
1. Windows fails to pass `test-c` with [this error](https://ci.appveyor.com/project/FloopCZ/coco/build/1.0.54/job/4eet7bdrtd4d5r9u) (WindowsError: [Error 2] The system cannot find the file specified). I am not sure what file is it missing, maybe there is something more that has to be done before running `test-c`? @brockho will probably know more.
2. Ubuntu Python 2 fails to pass postprocessing tests with [this error](https://circleci.com/gh/FloopCZ/coco/176) (Test failed: error while running bibtex on …
> [WIP] Improve continuous integration

- code-experiments/tools/cocoutils.py
- do.py
We can now pass "install-user" or "install-home=_directory_" as an additional argument to change Python package install location. The default when unspecified is to install to site packages, which works with conda and should work with virtualenv or any other environment manager, I think. The former default was to install to user packages, so to get the exact same behavior as before, we need to pass "install-user" now. I've updated help with relevant usage information and marked the commands that are affected by these new arguments.
> Added option to specify Python package install location

- code-postprocessing/cocopp/rungeneric.py
The issue itself is resolved. Still prints out that foreground algorithm list is changed from empty set to whatever, though. See second last line in the output below. Should read `foreground_algorithm_list: from ['.\\CMAES', '.\\DEAE'] to ['.\\CMAES', '.\\JADE']`, in my opinion. If that's any concern, we can open an issue for it, I think.
```
In [2]: import cocopp
In [3]: cocopp.main("CMAES DEAE")
Post-processing (2+): will generate output data in folder ppdata
this might take several minutes.
Data consistent according to consistency_check() in pproc.DataSet
using: .\CMAES
Data consistent according to consistency_check() in pproc.DataSet
using: .\DEAE
ECDF runlength ratio graphs...
C:\Users\randopt\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.528-py2.7.egg\cocopp\comp2\pprldist …
```
> Reset foreground algorithm list if cocopp.main() is called.

- code-postprocessing/cocopp/comp2/ppscatter.py
- code-postprocessing/cocopp/compall/ppfigs.py
- code-postprocessing/cocopp/genericsettings.py
- code-postprocessing/cocopp/ppfig.py
- code-postprocessing/cocopp/ppfigdim.py
- code-postprocessing/cocopp/ppfigparam.py
Font sizes returned are for use in the plot, so ppfig seemed appropriate.
> closes issue #1503

- code-postprocessing/cocopp/rungeneric1.py
- code-postprocessing/cocopp/rungenericmany.py
WARNING: dirty fix
`Data consistent according to consistency_check() in pproc.DataSet using: whatever` now get printed **_before_** `Post-processing (2+): will generate output data in folder ppdata\whatever`. No trivial way to work around it. FYI
> closes issue #1497

- code-postprocessing/cocopp/findfiles.py
- code-postprocessing/cocopp/pproc.py
- code-postprocessing/cocopp/test.py
Unfortunately, I still see many error leaks via valgrind on the Mac CI slave (devel-test2 branch). Don't know whether this is due to the bad support for OSX or really my fault (did not change anything on the `C` side).
> closes issue #35

- code-postprocessing/cocopp/__init__.py
- code-postprocessing/cocopp/bestalg.py
- code-postprocessing/cocopp/cococommands.py
- code-postprocessing/cocopp/ppfig.py
- code-postprocessing/cocopp/pproc.py
In order to do so, I
* added `from . import config` in `__init__.py`
* added `relative_load=False` when reference algorithm is loaded in `pproc.py`
In addition, I cleaned up paths in doctests wherever `os.chdir` is used (needs to be made nicer, i.e. by removing usage of `os.chdir` as much as possible).
> solves #1523

- do.py
Plus some make-up on do.py. Should still be easy enough to distinguish which changes are related to the issue.
> Make verbose default for c builds, add quiet option (#1623)

- code-postprocessing/cocopp/compall/pptables.py
...by not writing the LaTeX commands with every dimension (40-D came first in `cocopp_commands.tex` after we introduced the sorting of the dimension; this caused the bug when less algorithms have data in 40-D than in the other dimensions).
> solving issue #1658

- code-postprocessing/cocopp/pptable.py
Now the maximal width is defined as 3 chars, which cancels the precision prescription. The latter lead to irritating rounding results as shown in #1689
> small format adjustment addressing #1689

- code-experiments/src/f_gallagher.c
- code-experiments/src/f_lunacek_bi_rastrigin.c
- code-experiments/src/transform_vars_blockrotation_helpers.c
- code-experiments/src/transform_vars_permutation_helpers.c
It removes the usage of `coco_random.c` for the random permutations, for the block rotations as well as for the definition of the Gallagher and Lunacek Bi-Rastrigin functions.
> Kostas ls removing coco random new

- code-experiments/tools/cocoutils.py
- do.py
Hi
I think that it's a bad idea to use  `locate` in `do.py` to search for `jni.h` header file
* it requires `locate`
* can find the wrong file (happened to me)
If we search for a  `java` binary we can find `jre` or `jdk` directory and then get to the `include` folder.
Also in java 10 there is no `javah` binary, only `javac` with flag `-h`.
> change java path search + java 10 support 

- code-postprocessing/cocopp/pplogloss.py
Updated to use recent versions of matplotlib, which
deprecate `mlab.prctile` in favor of `numpy.percentile`.
> Fixes https://github.com/numbbo/coco/issues/1917

- code-postprocessing/cocopp/comp2/pprldistr2.py
UserWarning: FixedFormatter should only be used together with FixedLocator
by setting the xticks before their labels.
> Silence matplotlib 3.3.2 warning

- code-postprocessing/cocopp/compall/pprldmany.py
- code-postprocessing/cocopp/genericsettings.py
Description:
The x-limits for the ECDF plots were hard-coded to 1e7. We expose cocopp.compall.pprldmany.x_limit to cocopp.genericsettings as it is done already for the expensive setting.
Testing: 
I am not sure how to test that it works.
> x-limits in plots to be exposed in genericsettings Issue: 1662

- .circleci/config.yml
It seems a recent update on the CircleCI machine broke the tests as the installed modules were not found anymore. This PR consists of one single commit with is the merge of 4 commits as I hadd to add the option in a few places  (reproduced here for history)
- add install-user option in circleci
- correct mistake in circleci
- as expected, install-user also needed to install cocopp
- install-user in do.py test-* as well
> Fix the CircleCI broken pipe

- .github/workflows/cmake.yml
- code-experiments/build/c/CMakeLists.txt
- code-experiments/build/c/Makefile.in
- code-experiments/build/c/README.md
- code-experiments/build/c/meson.build
CMake and meson are build systems that have both gained popularity. This PR adds example build files for both so that users might use them as starting points if their project already uses CMake or meson. It should also be a good option for users on Windows where CMake can generate Visual Studio project files.
> Experiment: Add example CMake and meson build files

- code-experiments/src/c_linear.c
- code-experiments/src/coco.h
- code-experiments/src/coco_archive.c
- code-experiments/src/coco_observer.c
- code-experiments/src/coco_runtime_c.c
- code-experiments/src/coco_string.c
- code-experiments/src/coco_utilities.c
- code-experiments/src/f_bueche_rastrigin.c
- code-experiments/src/f_gallagher.c
- code-experiments/src/logger_bbob.c
- code-experiments/src/mo_avl_tree.c
- code-experiments/src/suite_biobj_utilities.c
- code-experiments/src/transform_vars_blockrotation.c
- code-experiments/src/transform_vars_blockrotation_helpers.c
- code-experiments/src/transform_vars_gallagher_blockrotation.c
Lots of small code fixes to catch more edge cases, remove dead code.
> Experiment: Lots of small C code fixes

- code-experiments/src/transform_vars_blockrotation.c
Largely a cosmetic change for future reference to clarify what the testcase is meant to test. Closes  issue #2072.
> Clarity test case code.

- do.py
During development it is useful to be able to amalgamate the sources without actually building them.  This PR splits the build-c subcommand into two parts, the amalgamation and the actual build.
> Add amalgamte-c command to do.py

- code-experiments/build/rust/Cargo.toml
- code-experiments/build/rust/coco-sys/Cargo.toml
- code-experiments/build/rust/src/lib.rs
This has three changes:
- Added missing `Suite::problem_by_function_dimension_instance` function
- Prevent `Problem` from outliving its `Suite`
- Incorporate internal `C` code changes into the Rust package
> Update Rust bindings.

- .gitignore
- code-experiments/build/c/.gitignore
- code-experiments/build/python/.gitignore
- code-experiments/examples/.gitignore
- code-experiments/test/integration-test/.gitignore
- code-experiments/test/unit-test/.gitignore
This covers the following commands:
- `build-c`
- `run-c`
- `test-c`
- `build-python`
- `build-rust`
- `run-rust`
- `test-rust`
It does not cover:
- `run-python`
- `*-java`
- `*-matlab`
This is only due to me not having these setup on my computer, but they would be easy to add for someone who has them.
> Add `.gitignore` files for c and python.

- code-experiments/build/rust/README.md
Hi!
I've been playing around with Rust and COCO and noticed that there is a minor mistake in Rust build instructions.
Running `cargo install bindgen` results in following error:
```
❯ cargo install bindgen
Updating crates.io index
error: there is nothing to install in `bindgen v0.63.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.
```
Looking at [`crates.io`](https://crates.io/crates/bindgen-cli/versions) it seems that `bindgen-cli` is published separately since October 2022 (done [here](https://github.com/rust-lang/rust-bindgen/commit/0296f9e86c7756e718b6b82836ce1e09b5f8d08a) most likely). 
Suggesting this change, because as I'm just starting playing …
> Fix Rust's readme
